---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: solaris10-minimal
    driver:
      provider: virtualbox
      box: tnarik/solaris10-minimal-with-chef
#  - name: ubuntu-12.04
#  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[cvs_wrapper::default]
    attributes:
